development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c7ea833d5872ff837bc446f3d4e08fde@soapfish.redistogo.com:10002
  channel_prefix: hashgram-backend_production
